### ISSUE TITLE
App fails to bind to gateway on Android 11

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-ping-android#158]
... So you get the screen saying that the gateway isn't installed.

I'm 60% confident I tried an early version of the Ping app on Android 11 and it worked, so if I'm not making that up, then we must've changed something that dropped Android 11 support.

I've already uninstalled and reinstalled both apps but the issue persists.

**Comment by Filmaluco** [comment]
Hi @gnarea, @sdsantos tasked me with taking a quick look.
I was able to reproduce the issue. I think it might be related with changes made to Package Visibility and security with Android 11.

https://developer.android.com/training/package-visibility/declaring#package-name

It appears we now have to declare within the app manifests all apps we interact externally.

---

While we were doing this, we also need to prepare for Android 12 that takes this changes a step further. 
https://developer.android.com/about/versions/12/behavior-changes-12

---

Bind in working in previous Android versions, bu we found an issue after binding.

```
Process: tech.relaycorp.ping, PID: 11570
    tech.relaycorp.ping.domain.InvalidIdentityCertificate: tech.relaycorp.awaladroid.endpoint.InvalidThirdPartyEndpoint: Invalid identity certificate
    ...
 Caused by: tech.relaycorp.relaynet.wrappers.x509.CertificateException: Certificate already expired
```
   
Do you know what it might be?

---

About the fix and the update to Android 12, we estimate half a day's work.

**Comment by gnarea** [comment]
Thanks @Filmaluco!

Re: CI issue with gateway app, it runs on Linux so that might have something to do with -- especially given that one of the dependencies had issues on macOS. Either way, you could try adding `--scan` to https://github.com/relaycorp/relaynet-gateway-android/blob/d2a7fa5b03256dbc08058e89b995e9b1e1d63306/.github/workflows/ci-cd.yml#L32 -- [here's an example in the Ping app](https://github.com/relaycorp/awala-ping-android/blob/4f52ba9d9d4eccb31847844f036fa340e579d01c/.github/workflows/ci-cd.yml#L32).

**Comment by sdsantos** [comment]
Maybe `security/snyk` should only run when the rest of the tasks are successful?

**Comment by gnarea** [comment]
I just reported the issue to Snyk -- they shouldn't be counting public repos towards that limit.

Until they fix that, Kodiak won't work (so the `automerge` label wouldn't merge anything), but I can manually merge PRs from GitHUb.
